### ISSUE TITLE
Path must be a string notification

### ISSUE THREAD

**Issue by erikverb** [Tutrox/scss-powertools#47]
![image](https://user-images.githubusercontent.com/7166388/52803214-469fab00-308a-11e9-9946-671071e63331.png)

The notification seems not to affect the output

**Comment by Klooven** [comment]
Does this happen on the current development branch? You can try installing straight from master using `npm install Tutrox/scss-powertools`...

**Comment by erikverb** [comment]
Yes, it happens

**Comment by Klooven** [comment]
This seems to happen because of Windows' way to handle directory listings with `\` instead of `/`. I'll think on this...

**Comment by Klooven** [comment]
I'll investigate this as v2 is getting ready. We'll be using a CI running both Windows and Linux, so that will hopefully catch issues related to a specific OS.

#1 has more details

**Comment by Klooven** [comment]
Can't be reproduced anymore
